#!/usr/bin/env python3
  
import sys
import pandas as pd
import matplotlib.pyplot as plt

file_name = sys.argv[1]
x_variable = sys.argv[2]
y_variable = sys.argv[3]
plot_type = sys.argv[4]

# Read CSV file into a DataFrame
df = pd.read_csv(file_name)

# Plot the X and Y variables
df[y_variable].rolling(window=180).mean().plot(label='180-day Moving Average', color='red', linewidth=2, zorder=10)
df.plot(x=x_variable, y=y_variable, kind=plot_type, label=y_variable, zorder=1)

# Show the plot
plt.xlabel(x_variable)
plt.ylabel(y_variable)
plt.title(f"{y_variable} vs {x_variable}")
plt.xticks(rotation=45)
plt.legend()

# Save plot as a PNG image
plt.savefig(f"{y_variable}_vs_{x_variable}.png", dpi=300, bbox_inches='tight')

